'use client';

import { ChangeEvent, DragEvent, useEffect, useMemo, useState } from "react";
import DOMPurify from "isomorphic-dompurify";
import { saveAs } from "file-saver";

type StylePresetId = "classic" | "modern" | "executive";

type StylePreset = {
  id: StylePresetId;
  name: string;
  description: string;
  accent: string;
  swatch: string;
};

type FormatterOptions = {
  justify: boolean;
  tidySpacing: boolean;
  titleCaseHeadings: boolean;
  autoNumberHeadings: boolean;
  convertQuotes: boolean;
};

type FormatResponse = {
  base64: string;
  previewHtml: string;
  appliedPreset: StylePresetId;
};

const STYLE_PRESETS: StylePreset[] = [
  {
    id: "classic",
    name: "Classic Report",
    description: "Times New Roman, 12pt body, generous leading for academic or legal docs.",
    accent: "#1d4ed8",
    swatch: "bg-gradient-to-r from-sky-300 to-blue-500",
  },
  {
    id: "modern",
    name: "Modern Minimal",
    description: "Calibri-inspired, airy spacing, light accent for tech and marketing teams.",
    accent: "#0f766e",
    swatch: "bg-gradient-to-r from-emerald-300 to-teal-500",
  },
  {
    id: "executive",
    name: "Executive Brief",
    description: "Georgia headings, professional sans body, crisp layout for leadership decks.",
    accent: "#a16207",
    swatch: "bg-gradient-to-r from-amber-300 to-orange-500",
  },
];

const DEFAULT_OPTIONS: FormatterOptions = {
  justify: true,
  tidySpacing: true,
  titleCaseHeadings: true,
  autoNumberHeadings: false,
  convertQuotes: true,
};

const toggleCopy: Record<keyof FormatterOptions, { title: string; hint: string }> = {
  justify: {
    title: "Justify body paragraphs",
    hint: "Align paragraph blocks edge-to-edge for a polished column feel.",
  },
  tidySpacing: {
    title: "Normalize spacing",
    hint: "Collapse repeated blank lines, fix rogue spacing, and trim trailing whitespace.",
  },
  titleCaseHeadings: {
    title: "Title case headings",
    hint: "Automatically convert headings to Title Case and remove shouty ALL CAPS.",
  },
  autoNumberHeadings: {
    title: "Auto-number headings",
    hint: "Generate multilevel numbering across H1–H3 without touching the text content.",
  },
  convertQuotes: {
    title: "Smart quotes",
    hint: "Swap straight quotes and apostrophes for curly, publication-grade glyphs.",
  },
};

const buildDownloadName = (original?: string | null, preset?: StylePreset) => {
  const base = original?.replace(/\.docx$/i, "") || "Document";
  return `${base}_${preset?.name.replace(/\s+/g, "") || "Formatted"}.docx`;
};

const base64ToBlob = (base64: string) => {
  const byteCharacters = globalThis.atob(base64);
  const byteNumbers = new Array(byteCharacters.length);
  for (let i = 0; i < byteCharacters.length; i += 1) {
    byteNumbers[i] = byteCharacters.charCodeAt(i);
  }
  const byteArray = new Uint8Array(byteNumbers);
  return new Blob([byteArray], {
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  });
};

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [preset, setPreset] = useState<StylePresetId>("classic");
  const [options, setOptions] = useState<FormatterOptions>(DEFAULT_OPTIONS);
  const [isDragging, setIsDragging] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [previewHtml, setPreviewHtml] = useState<string>("");
  const [formattedBlob, setFormattedBlob] = useState<Blob | null>(null);
  const [downloadName, setDownloadName] = useState<string>("Formatted.docx");
  const [lastRunPreset, setLastRunPreset] = useState<StylePresetId | null>(null);

  useEffect(() => {
    setDownloadName(buildDownloadName(file?.name, STYLE_PRESETS.find((p) => p.id === preset)));
  }, [file?.name, preset]);

  const sanitizedPreview = useMemo(() => {
    return DOMPurify.sanitize(previewHtml);
  }, [previewHtml]);

  const handleFileSelection = (incoming: File | null) => {
    if (!incoming) {
      setFile(null);
      return;
    }

    if (!incoming.name.toLowerCase().endsWith(".docx")) {
      setError("Please choose a .docx file generated by Microsoft Word or compatible editors.");
      return;
    }

    setError(null);
    setFile(incoming);
    setPreviewHtml("");
    setFormattedBlob(null);
  };

  const onInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    const incoming = event.target.files?.[0] ?? null;
    handleFileSelection(incoming);
  };

  const onDrop = (event: DragEvent<HTMLLabelElement>) => {
    event.preventDefault();
    setIsDragging(false);
    const incoming = event.dataTransfer.files[0];
    handleFileSelection(incoming ?? null);
  };

  const toggleOption = (key: keyof FormatterOptions) => {
    setOptions((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const performFormat = async () => {
    if (!file) {
      setError("Import a Word document first to unlock formatting.");
      return;
    }

    try {
      setIsProcessing(true);
      setError(null);
      const formData = new FormData();
      formData.append("file", file);
      formData.append("preset", preset);
      (Object.keys(options) as (keyof FormatterOptions)[]).forEach((key) => {
        formData.append(key, String(options[key]));
      });

      const response = await fetch("/api/format", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const payload = await response.json().catch(() => ({}));
        throw new Error(payload.error ?? "Formatting failed. Please try again.");
      }

      const data: FormatResponse = await response.json();
      const blob = base64ToBlob(data.base64);
      setFormattedBlob(blob);
      setPreviewHtml(data.previewHtml);
      setLastRunPreset(data.appliedPreset);
      setDownloadName(buildDownloadName(file.name, STYLE_PRESETS.find((p) => p.id === data.appliedPreset)));
    } catch (caught) {
      setFormattedBlob(null);
      setPreviewHtml("");
      setLastRunPreset(null);
      setError(caught instanceof Error ? caught.message : "An unexpected error occurred.");
    } finally {
      setIsProcessing(false);
    }
  };

  const download = () => {
    if (!formattedBlob) return;
    saveAs(formattedBlob, downloadName);
  };

  return (
    <main className="mx-auto flex min-h-screen w-full max-w-6xl flex-col gap-10 px-6 py-12 lg:flex-row lg:gap-12 lg:px-12">
      <section className="w-full max-w-xl space-y-10">
        <header className="space-y-4">
          <p className="inline-flex items-center gap-2 rounded-full bg-slate-900 px-4 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-white">
            Word Format Studio
          </p>
          <h1 className="text-4xl font-semibold tracking-tight text-slate-900 lg:text-5xl">
            Elevate Word documents with studio-grade formatting in seconds.
          </h1>
          <p className="text-base leading-7 text-slate-600">
            Import a .docx file, pick a presentation-ready preset, and export a polished version with consistent typography, spacing, and optional automated numbering.
          </p>
        </header>

        <div>
          <h2 className="text-sm font-semibold uppercase tracking-[0.3em] text-slate-500">Step 1</h2>
          <p className="mt-2 text-xl font-semibold text-slate-900">Drop your Word document</p>
          <label
            onDragOver={(event) => {
              event.preventDefault();
              setIsDragging(true);
            }}
            onDragLeave={() => setIsDragging(false)}
            onDrop={onDrop}
            className={`mt-4 flex cursor-pointer flex-col items-center justify-center rounded-3xl border-2 border-dashed px-6 py-10 text-center transition-all ${isDragging ? "border-slate-900 bg-slate-100" : "border-slate-300 bg-slate-50 hover:border-slate-400"}`}
          >
            <input className="hidden" type="file" accept=".docx" onChange={onInputChange} />
            <div className="flex h-16 w-16 items-center justify-center rounded-full bg-white shadow-sm ring-1 ring-slate-200">
              <span className="text-2xl font-semibold text-slate-900">.docx</span>
            </div>
            <p className="mt-4 text-base font-medium text-slate-900">
              Drag & drop your Word file or <span className="underline">browse</span>
            </p>
            <p className="mt-1 text-sm text-slate-500">We keep everything on-device—your file never leaves this session.</p>
            {file && (
              <div className="mt-6 w-full rounded-2xl bg-white p-4 text-left shadow-sm ring-1 ring-slate-200">
                <p className="truncate text-sm font-medium text-slate-900">{file.name}</p>
                <p className="text-xs text-slate-500">{(file.size / 1024).toFixed(1)} KB</p>
              </div>
            )}
          </label>
        </div>

        <div className="space-y-5">
          <div>
            <h2 className="text-sm font-semibold uppercase tracking-[0.3em] text-slate-500">Step 2</h2>
            <p className="mt-2 text-xl font-semibold text-slate-900">Choose a formatting preset</p>
          </div>
          <div className="grid gap-4 lg:grid-cols-3">
            {STYLE_PRESETS.map((item) => (
              <button
                key={item.id}
                type="button"
                onClick={() => setPreset(item.id)}
                className={`group relative flex h-full flex-col justify-between rounded-3xl border px-5 py-6 text-left transition-all ${preset === item.id ? "border-slate-900 shadow-lg shadow-slate-200/70" : "border-slate-200 hover:border-slate-400 hover:shadow-md hover:shadow-slate-200/60"}`}
              >
                <span className={`absolute inset-x-0 top-0 h-1 rounded-t-3xl ${item.swatch}`} />
                <div className="mt-2 space-y-3">
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-semibold text-slate-900">{item.name}</h3>
                    <span
                      className={`flex h-8 w-8 items-center justify-center rounded-full border border-slate-200 text-xs font-semibold uppercase tracking-widest ${preset === item.id ? "bg-slate-900 text-white" : "bg-white text-slate-500"}`}
                    >
                      {preset === item.id ? "ON" : "OFF"}
                    </span>
                  </div>
                  <p className="text-sm leading-6 text-slate-600">{item.description}</p>
                </div>
                <div className="mt-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.25em] text-slate-400">
                  <span className="inline-flex h-2 w-8 rounded-full" style={{ background: item.accent }} />
                  {item.id}
                </div>
              </button>
            ))}
          </div>
        </div>

        <div className="space-y-5">
          <div>
            <h2 className="text-sm font-semibold uppercase tracking-[0.3em] text-slate-500">Step 3</h2>
            <p className="mt-2 text-xl font-semibold text-slate-900">Fine-tune the polish</p>
          </div>

          <div className="space-y-3">
            {(Object.keys(options) as (keyof FormatterOptions)[]).map((key) => {
              const copy = toggleCopy[key];
              const active = options[key];
              return (
                <button
                  key={key}
                  type="button"
                  onClick={() => toggleOption(key)}
                  className={`w-full rounded-3xl border px-5 py-4 text-left transition-all ${active ? "border-slate-900 bg-slate-900 text-white shadow-xl shadow-slate-400/30" : "border-slate-200 bg-white text-slate-700 hover:border-slate-400 hover:bg-slate-50"}`}
                >
                  <p className="text-base font-semibold">{copy.title}</p>
                  <p className="mt-1 text-sm opacity-80">{copy.hint}</p>
                </button>
              );
            })}
          </div>
        </div>

        <div className="space-y-3">
          <button
            type="button"
            onClick={performFormat}
            disabled={isProcessing}
            className="inline-flex w-full items-center justify-center gap-3 rounded-3xl bg-slate-900 px-6 py-4 text-lg font-semibold text-white transition hover:bg-slate-700 disabled:cursor-not-allowed disabled:bg-slate-400"
          >
            {isProcessing ? "Formatting..." : "Generate formatted Word file"}
          </button>
          {error && <p className="rounded-2xl bg-rose-50 px-4 py-3 text-sm font-medium text-rose-600">{error}</p>}
          {formattedBlob && !error && (
            <div className="rounded-2xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">
              <p className="font-medium">
                Ready! {lastRunPreset ? `Applied the ${STYLE_PRESETS.find((item) => item.id === lastRunPreset)?.name} preset.` : ""}
              </p>
              <p className="text-xs opacity-80">Review the preview and export the polished .docx file.</p>
            </div>
          )}
        </div>
      </section>

      <aside className="w-full flex-1 rounded-[2.5rem] border border-slate-200 bg-white/70 px-8 py-10 shadow-xl shadow-slate-200/60 backdrop-blur lg:sticky lg:top-8">
        <div className="flex items-center justify-between">
          <p className="text-xs uppercase tracking-[0.3em] text-slate-400">Live preview</p>
          <span className="rounded-full border border-slate-200 px-3 py-1 text-xs font-medium text-slate-500">
            {formattedBlob ? "Formatted" : "Awaiting document"}
          </span>
        </div>
        <div className="mt-6 h-[520px] overflow-hidden overflow-y-auto rounded-[1.75rem] border border-slate-200 bg-white p-10 shadow-inner">
          {sanitizedPreview ? (
            <article
              className="prose prose-slate max-w-none"
              dangerouslySetInnerHTML={{ __html: sanitizedPreview }}
            />
          ) : (
            <div className="flex h-full flex-col items-center justify-center gap-4 text-center text-slate-400">
              <p className="text-lg font-semibold">Your upgraded document will appear here.</p>
              <p className="text-sm leading-6">
                Upload a .docx file and run the formatter to inspect headings, spacing, and typography before exporting.
              </p>
            </div>
          )}
        </div>
        <div className="mt-6 flex flex-col items-start gap-3">
          <button
            type="button"
            onClick={download}
            disabled={!formattedBlob}
            className="inline-flex items-center gap-3 rounded-2xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-700 disabled:cursor-not-allowed disabled:bg-slate-400"
          >
            Download formatted .docx
          </button>
          <p className="text-xs text-slate-500">
            File name: <span className="font-medium text-slate-900">{downloadName}</span>
          </p>
        </div>
      </aside>
    </main>
  );
}
